title: Site

sections:
  pages:
    type: pages
    templates:
      - home
      - globals
      - webflow-index
      - default

  globals:
    type: pages
    label: Globals
    parent: site.find("global")
    templates:
      - doc-master

  handbooks:
    type: pages
    label: Handbooks
    parent: site.find("sites")
    templates:
      - doc-client

  drafts:
    type: pages
    status: draft

  content:
    type: fields
    fields:
      site_description:
        type: textarea
        label: Site Description
      opengraph_image:
        type: files
        label: OpenGraph Image
        max: 1
        uploads:
          template: site-image
        query: site.files.template("site-image")
      favicon:
        type: files
        label: Favicon
        max: 1
        uploads:
          template: site-image
        query: site.files.template("site-image")
